driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: macosx-10.10
    run_list:
      - build-essential
      - homebrew
    driver:
      box: jhcook/osx-yosemite-10.10
      username: vagrant
      customize:
        cpus: 2
        memory: 8192

suites:
- name: default
  run_list:
  - recipe[postgresql]

- name: contrib
  run_list:
  - recipe[postgresql::contrib]
  excludes: [ "macosx-10.10" ] # macOS doesn't have contribs
  attributes:
    postgresql:
      password:
        postgres: "iloverandompasswordsbutthiswilldo"

- name: apt-pgdg-client
  run_list:
  - recipe[apt]
  - recipe[postgresql]
  excludes: [ "centos-6.8", "centos-7.2", "opensuse-13.2", "opensuse-leap-42.1", "fedora-24", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"
      client:
        packages: [ "postgresql-client-9.4", "libpq-dev" ]

- name: yum-pgdg-client
  run_list:
  - recipe[postgresql]
  excludes: [ "ubuntu-12.04", "ubuntu-14.04", "ubuntu-16.04", "debian-7.11", "debian-8.5", "opensuse-13.2", "opensuse-leap-42.1", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      client:
        packages: [ "postgresql94" ]

- name: ruby
  run_list:
  - recipe[postgresql::ruby]

- name: server
  run_list:
  - recipe[postgresql::ruby]
  - recipe[postgresql::server]
  attributes:
    postgresql:
      password:
        postgres: "iloverandompasswordsbutthiswilldo"

- name: apt-pgdg-server
  run_list:
  - recipe[apt]
  - recipe[postgresql::ruby]
  - recipe[postgresql::server]
  excludes: [ "centos-6.8", "centos-7.2", "opensuse-13.2", "opensuse-leap-42.1", "fedora-23", "fedora-24", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"
      dir: '/etc/postgresql/9.4/main'
      server:
        service_name: "postgresql"
        packages: [ "postgresql-9.4" ]
      client:
        packages: [ "postgresql-client-9.4", "libpq-dev" ]
      password:
        postgres: "iloverandompasswordsbutthiswilldo"
      config:
        ssl_cert_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
        ssl_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"

- name: yum-pgdg-server
  run_list:
  - recipe[postgresql::ruby]
  - recipe[postgresql::server]
  excludes: [ "ubuntu-12.04", "ubuntu-14.04", "ubuntu-16.04", "debian-8.5", "opensuse-13.2", "opensuse-leap-42.1", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      server:
        packages: [ "postgresql94-server" ]
        service_name: "postgresql-9.4"
      client:
        packages: [ "postgresql94", "postgresql94-devel" ]
      setup_script: "postgresql94-setup"
      password:
        postgres: "iloverandompasswordsbutthiswilldo"

- name: apt-pgdg-client-ruby
  run_list:
  - recipe[apt]
  - recipe[postgresql]
  - recipe[postgresql::ruby]
  excludes: [ "centos-6.8", "centos-7.2", "opensuse-13.2", "opensuse-leap-42.1", "fedora-23", "fedora-24", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"
      client:
        packages: [ "postgresql-client-9.4", "libpq-dev" ]

- name: yum-pgdg-client-ruby
  run_list:
  - recipe[postgresql]
  - recipe[postgresql::ruby]
  excludes: [ "ubuntu-12.04", "ubuntu-14.04", "ubuntu-16.04", "debian-7.11", "debian-8.5", "opensuse-13.2", "opensuse-leap-42.1", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      client:
        packages: [ "postgresql94", "postgresql94-devel" ]

- name: apt-pgdg-server-pg_stat_statements
  run_list:
  - recipe[apt]
  - recipe[postgresql::ruby]
  - recipe[postgresql::contrib]
  excludes: [ "centos-6.8", "centos-7.2", "opensuse-13.1", "opensuse-13.2", "fedora-23", "fedora-24", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"
      dir: '/etc/postgresql/9.4/main'
      server:
        service_name: "postgresql"
        packages: [ "postgresql-9.4" ]
      client:
        packages: [ "postgresql-client-9.4", "libpq-dev" ]
      password:
        postgres: "iloverandompasswordsbutthiswilldo"
      config:
        shared_preload_libraries: "pg_stat_statements"
        ssl_cert_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
        ssl_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
      contrib:
        extensions:
          - pg_stat_statements

- name: yum-pgdg-server-pg_stat_statements
  run_list:
  - recipe[postgresql::ruby]
  - recipe[postgresql::contrib]
  excludes: [ "centos-6.8", "ubuntu-12.04", "ubuntu-14.04", "ubuntu-16.04", "debian-8.5", "opensuse-13.2", "opensuse-leap-42-1", "macosx-10.10" ]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      setup_script: "postgresql94-setup"
      server:
        packages: [ "postgresql94-server" ]
        service_name: "postgresql-9.4"
      password:
        postgres: "iloverandompasswordsbutthiswilldo"
      config:
        shared_preload_libraries: "pg_stat_statements"
      contrib:
        extensions:
          - pg_stat_statements
